#
# Framework
#
# underscore or sage
wp_starter_theme: underscore
bootstrap: false
# genericons or fontawesome
web_font: genericons

#
# WordPress Theme name
#
theme_dir_name: vavg

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: ''

#
# Virtual Machine Settings
#
memory: 2018
cpus: 2

#
# Network Settings
#
hostname: vavg.example.com
ip: 192.168.33.10
sync_folder: .

#
# WordPress Database
#
db_prefix: wp_
db_host: 192.168.33.10

#
# WordPress User
#
admin_user: admin
admin_pass: admin
admin_email: vccw@example.com

#
# WordPress Settings
#
version: latest
lang: en_US

#
# The values of wp-config.php
#
force_ssl_admin: false
wp_debug: true
savequeries: true

#
# Theme unit testing
#
theme_unit_test: true
theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins:
  - ajax-thumbnail-rebuild
  - debug-bar
  - debug-bar-actions-and-filters-addon
  - debug-bar-console
  - debug-bar-cron
  - debug-bar-extender
  - debug-bar-slow-actions
  - dynamic-hostname
  - log-deprecated-notices
  - log-viewer
  - jetpack
  - monster-widget
  - mw-wp-form
  - rewrite-rules-inspector
  - simply-show-ids
  - smart-custom-fields
  - theme-check
  - user-switching
  - va-simple-expires
  - wordpress-importer
  - wordpress-seo
  - wp-multibyte-patch
  - wp-sweep
