#!/bin/sh
PROGNAME=$(basename $0)
VERSION="1.0.0"

usage() {
    echo "Usage: $PROGNAME [OPTIONS] FILE"
    echo "  This script is ~."
    echo
    echo "Options:"
    echo "  -h, Help"
    echo "  -v, Version"
    echo "  -i, Install"
    echo "  -s, Start"
    echo
    exit 1
}

for OPT in $*
do
    case $OPT in
        '-h' )
            usage
            exit 1
            ;;
        '-v' )
            echo $VERSION
            exit 1
            ;;
        '-i' )
            FLAG_i=1
            ;;
        '-s' )
            FLAG_s=1
            shift 2
            ;;
        *)
            echo "Internal error!" 1>&2
            exit 1
            ;;
    esac
    shift
done

if [ "$FLAG_i" ]; then
    latest=`curl -sI https://github.com/vccw-team/vccw/releases/latest | awk -F'/' '/^Location:/{print $NF}' | tr -d '\r'`
    wget https://github.com/vccw-team/vccw/archive/${latest}.zip

    if [ ! -e ${latest}.zip ];
    then
        echo "VCCW がダウンロードできませんでした。"
        exit 1
    fi

    unzip ${latest}.zip -d ./
    rm -rf ${latest}.zip
    cp -rf ./vccw-${latest}/* ./
    rm -rf ./vccw-${latest}/

    if [ ! -x "`which vagrant`" ] && [ ! -x "`which npm`" ] && [ ! -x "`which convert`" ] && [ ! -x "`which ruby`" ] && [ ! -x "`which sass`" ] && [ ! -x "`which compass`" ]; then
        echo "Vagrant、Node.js、ImageMagick、Ruby、Sass、Compass がインストールされていません。"
        exit 1
    fi

    if [ ! -x "`which vagrant`" ]; then
        echo "Vagrant がインストールされていません。"
    fi

    if [ ! -x "`which npm`" ]; then
        echo "Node.js がインストールされていません。"
    fi

    if [ ! -x "`which convert`" ]; then
        echo "ImageMagick がインストールされていません。"
    fi

    if [ ! -x "`which ruby`" ]; then
        echo "Ruby がインストールされていません。"
    fi

    if [ ! -x "`which sass`" ]; then
        echo "Sass がインストールされていません。"
    fi

    if [ ! -x "`which compass`" ]; then
        echo "Compass がインストールされていません。"
    fi

    if [ ! -x "`which vagrant`" ] || [ ! -x "`which npm`" ] || [ ! -x "`which convert`" ] || [ ! -x "`which ruby`" ] || [ ! -x "`which sass`" ] || [ ! -x "`which compass`" ]; then
        exit 1
    fi

    if [ ! -x "`which bower`" ] && [ "$(uname)" == "Darwin" ]; then
        sudo npm install bower –g
    elif [ ! -x "`which bower`" ]; then
        npm install bower –g
    fi

    if [ ! -x "`which gulp`" ] && [ "$(uname)" == "Darwin" ]; then
        sudo npm install gulp –g
    elif [ ! -x "`which bower`" ]; then
        npm install gulp –g
    fi

    if [ ! -e bower.json ]; then
        echo "bower.json がありません。"
    fi

    if [ ! -e package.json ]; then
        echo "package.json がありません。"
    fi

    if [ ! -e gulpfile.js ]; then
        echo "gulpfile.js がありません。"
    fi

    if [ ! -e config.rb ]; then
        echo "config.rb がありません。"
    fi

    if [ ! -e csscomb.json ]; then
        echo "csscomb.json がありません。"
    fi

    if [ ! -e bower.json ] || [ ! -e package.json ] || [ ! -e gulpfile.js ] || [ ! -e config.rb ] || [ ! -e csscomb.json ]; then
        exit 1
    fi

    bower install
    if [ "$(uname)" == "Darwin" ]; then
        sudo npm install
    else
        npm install
    fi

    gulp mkdir

    echo "VAVG のインストールが完了しました。"
fi

if [ "$FLAG_s" ]; then
    echo "VAVG を起動します。"
    vagrant up
    gulp
fi
